import React, { useDeferredValue, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Clock3, RefreshCw, Search, Truck } from 'lucide-react';
import { api } from '@/services/api';
import { MetricCard } from '@/components/shared/OperationalSourceBanner';

type Risk = 'on_track'|'late_departure'|'behind'|'stalled';
type LiveRoute = { routeId:string; routeCode:string; deliveryDate:string; transporterId:string; driverName:string; vin:string; status:string; risk:Risk; completedStops:number; totalStops:number; completionPct:number; deliveredPackages:number; totalPackages:number; stopsLastHour:number; projectedCompletionAt:string|null; projectedLateMinutes:number; inactiveMinutes:number; onBreak:boolean; routePaused:boolean; rescueCount:number; associatedRoutes:{routeCode:string}[]; isMultiRoute:boolean };
type Payload = { period:string|null; capturedAt:string|null; source:string; live:boolean; stale:boolean; needsData:boolean; needsReauth:boolean; message?:string; routeCount:number; summary:{assigned:number;inProgress:number;completed:number;behind:number;stalled:number;lateDepartures:number;multiRoute:number}; routes:LiveRoute[] };
const riskStyle:Record<Risk,string>={on_track:'bg-emerald-100 text-emerald-800',late_departure:'bg-amber-100 text-amber-800',behind:'bg-orange-100 text-orange-800',stalled:'bg-red-100 text-red-800'};
const time=(value:string|null)=>value?new Date(value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';

const RoutesPage:React.FC=()=>{
  const [search,setSearch]=useState(''); const [risk,setRisk]=useState<'all'|Risk>('all');
  const deferredSearch=useDeferredValue(search.trim().toLowerCase());
  const {data,isLoading,error,refetch,isFetching}=useQuery<Payload>({queryKey:['route-monitor-live'],queryFn:()=>api.get<Payload>('/route-monitor'),refetchInterval:5*60*1000,staleTime:4*60*1000});
  const searchableRoutes=useMemo(()=>(data?.routes||[]).map(route=>({route,searchText:`${route.driverName} ${route.transporterId} ${route.routeCode} ${route.vin}`.toLowerCase()})),[data?.routes]);
  const rows=useMemo(()=>searchableRoutes.filter(({route,searchText})=>(risk==='all'||route.risk===risk)&&searchText.includes(deferredSearch)).map(({route})=>route),[searchableRoutes,risk,deferredSearch]);
  if(isLoading)return <div className="rounded-xl border bg-white p-8">Loading live routes…</div>;
  if(error)return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800">Live routes could not be loaded. <button className="underline" onClick={()=>refetch()}>Retry</button></div>;
  const age=data?.capturedAt?Math.max(0,Math.round((Date.now()-Date.parse(data.capturedAt))/60000)):null;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold dark:text-white">Live Route Monitor</h1><p className="text-sm text-gray-500">Amazon Delivery Execution · {data?.period||'no operating day loaded'}</p></div><button onClick={()=>refetch()} disabled={isFetching} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw size={16} className={isFetching?'animate-spin':''}/>Refresh</button></header>
    <div className={`rounded-xl border p-4 ${data?.live?'border-emerald-200 bg-emerald-50 text-emerald-900':data?.stale&&data?.capturedAt?'border-amber-200 bg-amber-50 text-amber-900':'border-slate-200 bg-slate-50 text-slate-800'}`}><div className="flex items-center gap-2 font-semibold">{data?.live?<><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/>Live data</>:<><AlertTriangle size={17}/>{data?.capturedAt?'Data is stale':'Live data not connected'}</>}</div><p className="mt-1 text-sm">{data?.message||`${data?.routeCount||0} route assignments captured ${age===null?'at an unknown time':`${age} minute${age===1?'':'s'} ago`}. Auto-refreshes every five minutes.`}</p>{data?.needsReauth&&<p className="mt-2 text-sm font-semibold">Reconnect Amazon on the Connections screen.</p>}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Routes" value={data?.routeCount||0}/><MetricCard label="In progress" value={data?.summary.inProgress||0}/><MetricCard label="Completed" value={data?.summary.completed||0}/><MetricCard label="Behind" value={data?.summary.behind||0}/><MetricCard label="Stalled" value={data?.summary.stalled||0}/><MetricCard label="Late departures" value={data?.summary.lateDepartures||0}/></div>
    <section className="rounded-xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-3 border-b p-4 dark:border-slate-800"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-gray-400" size={16}/><input aria-label="Search live routes" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Driver, transporter, route, or VIN" className="w-full rounded-lg border py-2 pl-9 pr-3 dark:border-slate-700 dark:bg-slate-950"/></label><select aria-label="Risk filter" value={risk} onChange={e=>setRisk(e.target.value as typeof risk)} className="rounded-lg border px-3 dark:border-slate-700 dark:bg-slate-950"><option value="all">All conditions</option><option value="stalled">Stalled</option><option value="behind">Behind</option><option value="late_departure">Late departure</option><option value="on_track">On track</option></select></div>
      {rows.length===0?<div className="p-10 text-center text-gray-500"><Truck className="mx-auto mb-3"/><p className="font-medium">No live routes to display</p><p className="mt-1 text-sm">The monitor never substitutes weekly scorecard rows for live execution data.</p></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-slate-800"><tr><th className="p-3">Route / driver</th><th className="p-3">Condition</th><th className="p-3">Stops</th><th className="p-3">Pace</th><th className="p-3">Packages</th><th className="p-3">Projected finish</th><th className="p-3">Vehicle / assignment</th></tr></thead><tbody className="divide-y dark:divide-slate-800">{rows.map(r=><tr key={`${r.routeId}-${r.transporterId}`} className={r.risk==='stalled'?'bg-red-50/60':''}><td className="p-3"><div className="font-semibold dark:text-white">{r.routeCode}</div><div className="text-xs text-gray-500">{r.driverName||r.transporterId||'Unassigned'}</div></td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${riskStyle[r.risk]}`}>{r.risk.replace('_',' ')}</span>{r.onBreak&&<div className="mt-1 text-xs text-gray-500">On break</div>}{r.routePaused&&<div className="mt-1 text-xs text-red-600">Route paused</div>}</td><td className="p-3"><div className="font-semibold">{r.completedStops}/{r.totalStops}</div><div className="mt-1 h-1.5 w-24 rounded bg-gray-200"><div className="h-1.5 rounded bg-blue-500" style={{width:`${Math.min(100,r.completionPct)}%`}}/></div></td><td className="p-3"><div>{r.stopsLastHour} stops/hr</div>{r.inactiveMinutes>=30&&<div className="text-xs text-red-600">No event {r.inactiveMinutes}m</div>}</td><td className="p-3">{r.deliveredPackages}/{r.totalPackages}</td><td className="p-3"><div className="flex items-center gap-1"><Clock3 size={14}/>{time(r.projectedCompletionAt)}</div>{r.projectedLateMinutes>0&&<div className="text-xs font-semibold text-orange-600">{r.projectedLateMinutes}m late</div>}</td><td className="p-3"><div>{r.vin||'No VIN'}</div>{r.isMultiRoute&&<div className="text-xs text-blue-700">Multi-route: {r.associatedRoutes.map(a=>a.routeCode).join(', ')}</div>}{r.rescueCount>0&&<div className="text-xs font-semibold text-purple-700">{r.rescueCount} rescue action(s)</div>}</td></tr>)}</tbody></table></div>}<p className="border-t p-3 text-xs text-gray-500 dark:border-slate-800">Showing {rows.length} routes · Source: {data?.source}</p></section>
  </div>;
};
export default RoutesPage;
