import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Clock3, Database, FileCheck2, Landmark, RefreshCw, Send, ShieldCheck, Upload } from 'lucide-react';
import { api } from '@/services/api';

type Finding = { label?: string; value?: string | number | null; detail?: string; [k: string]: unknown };
type Evidence = { label?: string; path?: string; sha256?: string; source?: string; name?: string; [k: string]: unknown };
type ModuleCase = { moduleId: string; externalKey: string; status: string; disposition?: string | null; createdAt?: string; candidateCount: number; recoveredRoutes?: number | null; recoveredValue?: number | null; blockingEvidence: unknown[]; externalActionAuthorized: boolean; approvalStatus?: string | null; approvedBy?: string | null; submissionStatus?: string | null; submissionConfirmation?: string | null; findings: Finding[]; evidence: Evidence[]; sourcePath: string };
type Module = { id: string; displayName: string; description?: string; state: string; headline?: string; detail?: string; runner?: string; runnerExists: boolean; requiredInputs: unknown[]; hasSubmissionAdapter: boolean; schedule: string; caseCount: number; openCaseCount: number; recoveredValue: number; latestCase: ModuleCase | null };
type Payload = { generatedAt?: string; servedAt: string; needsData?: boolean; summary: { modules: number; active: number; readyForImport: number; cases: number; openCases: number; recoveredValue: number; submitted: number }; modules: Module[]; cases: ModuleCase[]; schedules: { id: string; name: string; cadence: string }[] };

const usd = (v?: number | null) => v == null ? '—' : v.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const when = (s?: string | null) => s ? new Date(s).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const pretty = (v?: string | null) => (v || 'unknown').replace(/_/g, ' ');
const stateMeta: Record<string, { label: string; cls: string }> = {
  active: { label: 'Live', cls: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200' },
  ready_for_import: { label: 'Needs data import', cls: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200' },
  foundation: { label: 'Foundation', cls: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300' },
};
const caseCls = (c: ModuleCase) => c.submissionStatus ? 'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-200' : c.status === 'closed' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200' : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200';

const ReimbursementReviewPage: React.FC = () => {
  const [moduleFilter, setModuleFilter] = useState('all');
  const [open, setOpen] = useState<string | null>(null);
  const { data, isLoading, error, refetch, isFetching } = useQuery<Payload>({ queryKey: ['reimbursement-review'], queryFn: () => api.get<Payload>('/modules'), staleTime: 60000 });
  const cases = useMemo(() => (data?.cases || []).filter((c) => moduleFilter === 'all' || c.moduleId === moduleFilter), [data, moduleFilter]);
  const nameOf = (id: string) => data?.modules.find((m) => m.id === id)?.displayName || id;

  if (isLoading) return <div className="rounded-xl border border-gray-200 bg-white p-8 text-center text-gray-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">Loading reimbursement modules…</div>;
  if (error || !data) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-200"><strong>Module status could not be loaded.</strong><button onClick={() => refetch()} className="ml-3 underline">Retry</button></div>;
  if (data.needsData) return <div className="rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900"><h1 className="text-xl font-semibold text-gray-900 dark:text-white">No reimbursement review data for this tenant</h1><p className="mt-2 text-sm text-gray-500 dark:text-slate-400">Connect this tenant’s Amazon Payments and accounting evidence sources to activate reimbursement review.</p></div>;

  const s = data.summary;
  const live = data.modules.filter((m) => m.state === 'active' && m.id !== 'executive_dashboard');
  const imports = data.modules.filter((m) => m.state === 'ready_for_import');
  const adapters = data.modules.filter((m) => m.hasSubmissionAdapter).length;
  const kpis = [
    { l: 'Live lanes', v: live.length + ' of ' + (live.length + imports.length), d: imports.length + ' waiting on data imports', i: <ShieldCheck size={20} /> },
    { l: 'Cases on file', v: String(s.cases), d: s.openCases + ' open · ' + s.submitted + ' submitted to Amazon', i: <FileCheck2 size={20} /> },
    { l: 'Recovered / claimed', v: usd(s.recoveredValue), d: 'Confirmed recoveries plus submitted claims', i: <Landmark size={20} /> },
    { l: 'Submission adapters', v: adapters + ' of ' + live.length, d: 'Live lanes able to file with Amazon after approval', i: <Send size={20} /> },
  ];

  return <div className="space-y-6 pb-10">
    <section className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
      <div><p className="text-sm font-semibold text-blue-600 dark:text-blue-400">Payment and reimbursement modules</p><h1 className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">Reimbursement Review</h1><p className="mt-1 max-w-3xl text-sm text-gray-500 dark:text-slate-400">Every Amazon payment lane checked against our own evidence. Findings become cases; cases need an explicit owner approval before anything is filed with Amazon.</p></div>
      <div className="flex flex-wrap items-center gap-2"><span className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs text-gray-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Status feed {when(data.generatedAt)}</span><button onClick={() => refetch()} disabled={isFetching} className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"><RefreshCw size={15} className={isFetching ? 'animate-spin' : ''} />Refresh</button></div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map((k) => <article key={k.l} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-slate-400">{k.l}</p><p className="mt-2 text-2xl font-bold text-gray-900 dark:text-white">{k.v}</p><p className="mt-1 text-xs text-gray-500 dark:text-slate-400">{k.d}</p></div><span className="rounded-lg bg-gray-100 p-2 text-gray-600 dark:bg-slate-800 dark:text-slate-300">{k.i}</span></div></article>)}</section>

    <section><h2 className="mb-3 font-semibold text-gray-900 dark:text-white">Live lanes</h2>
      <div className="grid gap-4 lg:grid-cols-3">{live.map((m) => { const lc = m.latestCase; return <article key={m.id} className="flex flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-gray-900 dark:text-white">{m.displayName}</h3><p className="mt-0.5 text-xs text-gray-500 dark:text-slate-400">{m.headline}</p></div><span className={'shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ' + stateMeta[m.state].cls}>{stateMeta[m.state].label}</span></div>
        <p className="mt-3 text-sm text-gray-600 dark:text-slate-300">{m.detail}</p>
        <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-gray-500 dark:text-slate-400">Schedule</dt><dd className="font-medium text-gray-900 dark:text-white">{m.schedule}</dd></div><div><dt className="text-xs text-gray-500 dark:text-slate-400">Files with Amazon</dt><dd className={'font-medium ' + (m.hasSubmissionAdapter ? 'text-emerald-700 dark:text-emerald-300' : 'text-amber-700 dark:text-amber-300')}>{m.hasSubmissionAdapter ? 'Yes — guarded adapter' : 'No — email approval only'}</dd></div><div><dt className="text-xs text-gray-500 dark:text-slate-400">Cases</dt><dd className="font-medium text-gray-900 dark:text-white">{m.caseCount}{m.openCaseCount ? ' · ' + m.openCaseCount + ' open' : ''}</dd></div><div><dt className="text-xs text-gray-500 dark:text-slate-400">Recovered</dt><dd className="font-medium text-gray-900 dark:text-white">{usd(m.recoveredValue)}</dd></div></dl>
        {lc ? <div className="mt-4 rounded-lg border border-gray-200 bg-gray-50 p-3 text-xs dark:border-slate-700 dark:bg-slate-950"><div className="flex items-center justify-between"><span className="font-semibold text-gray-900 dark:text-white">Latest: {lc.externalKey}</span><span className={'rounded-full px-2 py-0.5 font-semibold ' + caseCls(lc)}>{lc.submissionStatus ? 'submitted' : pretty(lc.status)}</span></div><p className="mt-1 text-gray-600 dark:text-slate-300">{pretty(lc.disposition)} · {when(lc.createdAt)}</p></div> : <div className="mt-4 rounded-lg border border-dashed border-gray-300 p-3 text-xs text-gray-500 dark:border-slate-700 dark:text-slate-400">No case yet</div>}
      </article>; })}</div></section>

    <section className="rounded-xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/70 dark:bg-amber-950/30"><div className="flex items-center gap-2 text-amber-900 dark:text-amber-200"><Upload size={18} /><h2 className="font-semibold">Lanes waiting on data imports</h2></div><p className="mt-1 text-sm text-amber-800 dark:text-amber-300">Reconcilers are built and tested but have never run against real data. Each needs its source exports before a case can be produced.</p>
      <div className="mt-4 grid gap-3 md:grid-cols-2">{imports.map((m) => <article key={m.id} className="rounded-lg border border-amber-200 bg-white p-4 dark:border-amber-800 dark:bg-slate-900"><h3 className="font-semibold text-gray-900 dark:text-white">{m.displayName}</h3><p className="mt-1 text-xs text-gray-500 dark:text-slate-400">{m.detail || m.description}</p>{m.requiredInputs.length > 0 && <ul className="mt-2 list-disc pl-5 text-xs text-gray-700 dark:text-slate-300">{m.requiredInputs.map((i, n) => <li key={n}>{typeof i === 'string' ? i : JSON.stringify(i)}</li>)}</ul>}<p className="mt-2 font-mono text-[11px] text-gray-500 dark:text-slate-400">{m.runner}{m.runnerExists ? '' : ' (missing)'}</p></article>)}</div></section>

    <section className="rounded-xl border border-gray-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <div className="flex flex-col gap-3 border-b border-gray-200 px-5 py-4 sm:flex-row sm:items-end sm:justify-between dark:border-slate-800"><div><h2 className="font-semibold text-gray-900 dark:text-white">Case ledger</h2><p className="text-xs text-gray-500 dark:text-slate-400">{cases.length} cases · click a row for findings, evidence hashes, and the approval trail</p></div><select value={moduleFilter} onChange={(e) => setModuleFilter(e.target.value)} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900 dark:text-white"><option value="all">All modules</option>{data.modules.filter((m) => m.caseCount > 0).map((m) => <option key={m.id} value={m.id}>{m.displayName}</option>)}</select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500 dark:bg-slate-950 dark:text-slate-400"><tr><th className="px-5 py-3">Case</th><th className="px-3 py-3">Module</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Disposition</th><th className="px-3 py-3 text-right">Candidates</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3">Approval</th><th className="px-3 py-3">Submission</th><th className="px-3 py-3">Created</th><th className="px-3 py-3" /></tr></thead>
        <tbody className="divide-y divide-gray-100 dark:divide-slate-800">{cases.map((c) => { const key = c.sourcePath; const isOpen = open === key; return <React.Fragment key={key}>
          <tr onClick={() => setOpen(isOpen ? null : key)} className="cursor-pointer text-gray-700 hover:bg-gray-50 dark:text-slate-200 dark:hover:bg-slate-800/60"><td className="px-5 py-3 font-medium text-gray-900 dark:text-white">{c.externalKey}</td><td className="px-3 py-3">{nameOf(c.moduleId)}</td><td className="px-3 py-3"><span className={'rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ' + caseCls(c)}>{pretty(c.status)}</span></td><td className="px-3 py-3">{pretty(c.disposition)}</td><td className="px-3 py-3 text-right tabular-nums">{c.candidateCount}</td><td className="px-3 py-3 text-right tabular-nums">{usd(c.recoveredValue)}</td><td className="px-3 py-3 text-xs">{c.approvalStatus ? <span className="inline-flex items-center gap-1 text-emerald-700 dark:text-emerald-300"><CheckCircle2 size={13} />{c.approvalStatus}{c.approvedBy ? ' · ' + c.approvedBy : ''}</span> : <span className="text-gray-400">not required</span>}</td><td className="px-3 py-3 text-xs">{c.submissionStatus ? <span className="inline-flex items-center gap-1 text-blue-700 dark:text-blue-300"><Send size={13} />{c.submissionStatus}{c.submissionConfirmation ? ' · ' + c.submissionConfirmation : ''}</span> : <span className="text-gray-400">—</span>}</td><td className="px-3 py-3 text-xs tabular-nums">{when(c.createdAt)}</td><td className="px-3 py-3 text-gray-400">{isOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}</td></tr>
          {isOpen && <tr className="bg-gray-50 dark:bg-slate-950"><td colSpan={10} className="px-5 py-4"><div className="grid gap-4 lg:grid-cols-2">
            <div><h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-slate-400">Findings ({c.findings.length})</h4><ul className="mt-2 space-y-1.5 text-xs text-gray-700 dark:text-slate-300">{c.findings.slice(0, 20).map((f, i) => <li key={i} className="rounded border border-gray-200 bg-white p-2 dark:border-slate-700 dark:bg-slate-900">{f.label ? <strong className="mr-1">{String(f.label)}:</strong> : null}{f.value != null ? <span className="mr-1 font-mono">{String(f.value)}</span> : null}<span>{typeof f === 'string' ? f : String(f.detail ?? JSON.stringify(f))}</span></li>)}</ul>{c.blockingEvidence.length > 0 && <p className="mt-2 flex items-center gap-1 text-xs text-amber-700 dark:text-amber-300"><AlertTriangle size={13} />{c.blockingEvidence.length} blocking evidence item(s)</p>}</div>
            <div><h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-slate-400">Evidence ({c.evidence.length})</h4><ul className="mt-2 space-y-1.5 text-xs">{c.evidence.map((e, i) => <li key={i} className="rounded border border-gray-200 bg-white p-2 font-mono text-[11px] text-gray-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">{e.label ? <span className="mr-1 font-sans font-semibold">{String(e.label)}</span> : null}{String(e.path ?? e.source ?? e.name ?? JSON.stringify(e))}{e.sha256 ? <span className="block text-gray-400">sha256 {String(e.sha256).slice(0, 16)}…</span> : null}</li>)}</ul><p className="mt-2 font-mono text-[11px] text-gray-400">{c.sourcePath}</p>{c.externalActionAuthorized ? <p className="mt-2 flex items-center gap-1 text-xs text-emerald-700 dark:text-emerald-300"><CheckCircle2 size={13} />External action was explicitly authorized</p> : <p className="mt-2 flex items-center gap-1 text-xs text-gray-500 dark:text-slate-400"><Clock3 size={13} />No external action authorized</p>}</div>
          </div></td></tr>}
        </React.Fragment>; })}</tbody></table></div></section>

    <section className="grid gap-4 lg:grid-cols-2">
      <article className="rounded-xl border border-gray-200 bg-white p-5 text-sm shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white"><Clock3 size={16} />Automation schedules</h3><ul className="mt-3 divide-y divide-gray-100 dark:divide-slate-800">{data.schedules.map((j) => <li key={j.id} className="flex items-center justify-between py-2"><span className="text-gray-700 dark:text-slate-200">{j.name}</span><span className="text-xs text-gray-500 dark:text-slate-400">{j.cadence} · <span className="font-mono">{j.id}</span></span></li>)}</ul><p className="mt-2 text-xs text-gray-500 dark:text-slate-400">Run health is checked from the OpenClaw automations inventory; live status moves here once module runners execute on AWS.</p></article>
      <article className="rounded-xl border border-blue-100 bg-blue-50 p-5 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-200"><h3 className="flex items-center gap-2 font-semibold"><Database size={16} />Control rules</h3><ul className="mt-2 list-disc space-y-1 pl-5"><li>Findings never auto-file. Every Amazon submission requires an exact, single-use owner approval on the original email thread.</li><li>Only Fixed Monthly has a guarded submission adapter today; Weekly Payments and C&amp;R stop at the approval email.</li><li>Evidence is hashed (sha256) at case creation; approvals are bound to those hashes.</li><li>Import lanes stay dormant until their source exports are provided — nothing is inferred.</li></ul></article>
    </section>
  </div>;
};

export default ReimbursementReviewPage;
